### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by raden** [LiquidSmooth-Old/android#11]
Got error during compilation (time mka liquid) for MAKO

target thumb C: libzopfli <= external/pigz/zopfli/blocksplitter.c
target thumb C: libzopfli <= external/pigz/zopfli/cache.c
target thumb C: libzopfli <= external/pigz/zopfli/deflate.c
external/pigz/zopfli/deflate.c: In function 'AddLZ77Data':
external/pigz/zopfli/deflate.c:240:25: warning: unused parameter 'expected_data_size' [-Wunused-parameter]
                  size_t expected_data_size,
                         ^
target thumb C: libzopfli <= external/pigz/zopfli/tree.c
target thumb C: libzopfli <= external/pigz/zopfli/lz77.c
external/pigz/zopfli/lz77.c: In function 'VerifyLenDist':
external/pigz/zopfli/lz77.c:80:54: warning: unused parameter 'datasize' [-Wunused-parameter]
 void VerifyLenDist(const unsigned char\* data, size_t datasize, size_t pos,
                                                      ^
target thumb C: libzopfli <= external/pigz/zopfli/hash.c
target thumb C: libzopfli <= external/pigz/zopfli/util.c
target thumb C: libzopfli <= external/pigz/zopfli/squeeze.c
target thumb C: libzopfli <= external/pigz/zopfli/katajainen.c
external/pigz/pigz.c: In function 'process':
external/pigz/pigz.c:3105:58: warning: signed and unsigned type in conditional expression [-Wsign-compare](fstat%28g.ind, &st%29 ? time%28NULL%29 : st.st_mtime) : 0;
                                                          ^
external/pigz/pigz.c: In function 'compress_thread':
external/pigz/pigz.c:1435:55: warning: 'temp' may be used uninitialized in this function [-Wmaybe-uninitialized]
                             temp->buf, temp->len, temp->len + len,
                                                       ^
make: **\* No rule to make target `vendor/lge/mako/proprietary/libAKM.so', needed by`/mnt/working-dir/out/target/product/mako/system/lib/libAKM.so'.  Stop.
make: **\* Waiting for unfinished jobs....

**Comment by deadman96385** [comment]
Now fixed
